# Generated by Django 4.1.2 on 2022-10-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_file_remove_chat_img_remove_chat_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_url',
            new_name='slug',
        ),
    ]
